const Server = require("./network/server");
const Game = require("./game/game");

const game = new Game({
  TPS: 25,
  MAX_CELL_PER_TICK: 50,
  IGNORE_BORDERS: false,
  CELL_LIMIT: 65536,
  QUADTREE_MAX_ITEMS: 16,
  QUADTREE_MAX_LEVEL: 16,
  MAP_HW: 14000,
  MAP_HH: 14000,
  MAP_HX: 0,
  MAP_HY: 0,
  BOT_COUNT: 30,
  SAFE_SPAWN_TRIES: 64,
  SAFE_SPAWN_RADIUS: 1.5,
  PELLET_COUNT: 1000,
  PELLET_SIZE: 10,
  VIRUS_COUNT: 0,
  VIRUS_SIZE: 125,
  VIRUS_FEED_TIMES: 7,
  VIRUS_SPLIT_BOOST: 780,
  VIRUS_MONOTONE_POP: false,
  MOTHER_CELL_COUNT: 0,
  MOTHER_CELL_SIZE: 149,
  PLAYER_SPEED: 1,
  PLAYER_SPAWN_DELAY: 1000,
  PLAYER_DECAY_SPEED: 0.01,
  PLAYER_DECAY_MIN_SIZE: 1000,
  PLAYER_AUTOSPLIT_SIZE: 0,
  PLAYER_MAX_CELLS: 100,
  PLAYER_SPAWN_SIZE: 1500,
  PLAYER_SPLIT_BOOST: 1000,
  PLAYER_SPLIT_DIST: 60,
  PLAYER_SPLIT_CAP: 255,
  PLAYER_MIN_SPLIT_SIZE: 60,
  PLAYER_MIN_EJECT_SIZE: 110,
  PLAYER_NO_MERGE_DELAY: 22,
  PLAYER_NO_COLLI_DELAY: 13,
  PLAYER_MERGE_TIME: 0,
  PLAYER_MERGE_INCREASE: 0.25,
  PLAYER_MERGE_NEW_VER: true,
  PLAYER_VIEW_SCALE: 1,
  PLAYER_DEAD_DELAY: 5,
  EJECT_DISPERSION: 0.1,
  EJECT_SIZE: 70,
  EJECT_LOSS: 66,
  EJECT_BOOST: 500,
  EJECT_DELAY: 1, // ms
  WORLD_RESTART_MULT: 0.75,
  WORLD_KILL_OVERSIZE: false,
  EAT_OVERLAP: 3,
  EAT_MULT: 1.140175425099138,
});
const server = new Server(game);
const engine = game.engine;

(async () => {
    await engine.init();
    await server.open();
    engine.start();
})();
